### ISSUE TITLE
Error when running PBMC10k-MLCB.ipynb

### ISSUE THREAD

**Issue by yuhanH** [adamgayoso/totalVI_reproducibility#2]
HI, Adam

I am running PBMC10k-MLCB.ipynb. However, when it comes to the `Create posterior` section, 
`adjusted_px_scale = full_posterior.sequential().get_normalized_denoised_expresssion(n_samples=N_SAMPLES, give_mean=True)` prints out the error.

AttributeError: 'TotalPosterior' object has no attribute 'get_normalized_denoised_expresssion'

I am curious how to fix it.  I am in the totalVI_main_staging branch of scVI. Thanks.

**Comment by adamgayoso** [comment]
Hello @yuhanH ,

Sorry for the inconvenience. The totalVI code is now in the master branch of scVI, there is also a tutorial there in `tests/notebooks`. I will update the code here asap.
